from quart import Quart, request
import os
import pandas as pd
import yfinance as yf

app = Quart(__name__)

stock_counter = {}  # here key is symbol name and value is index as counter
stock_df = {}  # here key is symbol name and value is one day price data
DATA_FROM_FILE = False
date = "2023-11-17"

stocks_list = ['AARTIIND', 'ABCAPITAL', 'ABFRL', 'ABSLAMC', 'ADANIPOWER', 'AMBUJACEM', 'APOLLOTYRE', 'APTUS', 'ASAHIINDIA', 'ASHOKLEY', 'ATGL', 'AUBANK', 'AWL', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BEL', 'BERGEPAINT', 'BHEL', 'BIOCON', 'BPCL', 'CAMPUS', 'CANBK', 'CENTRALBK', 'CGCL', 'CGPOWER', 'CHAMBLFERT', 'COALINDIA', 'CONCOR', 'CROMPTON', 'CUB', 'DABUR', 'DELHIVERY', 'DEVYANI', 'DLF', 'ELGIEQUIP', 'EMAMILTD', 'EXIDEIND', 'FACT', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GICRE', 'GMRINFRA', 'GODREJIND', 'GSPL', 'GUJGASLTD', 'HDFCLIFE', 'HINDALCO', 'HINDPETRO', 'HINDZINC', 'ICICIPRULI', 'IDBI', 'IDFC', 'IDFCFIRSTB', 'IGL', 'IIFL', 'INDHOTEL', 'INDIANB', 'INDUSTOWER', 'IOB', 'IOC', 'IRB', 'IRCTC', 'IRFC', 'ISEC', 'ITC', 'JINDALSTEL', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD', 'KALYANKJIL', 'KANSAINER', 'KEC', 'KIOCL', 'L&TFH', 'LAURUSLABS', 'LICHSGFIN', 'LICI', 'M&MFIN', 'MAHABANK', 'MARICO', 'MAXHEALTH', 'MOTHERSON', 'MSUMI', 'NAM-INDIA', 'NATIONALUM', 'NHPC', 'NIACL', 'NMDC', 'NTPC', 'NUVOCO', 'NYKAA', 'OIL', 'ONGC', 'PETRONET', 'PFC', 'PNB', 'POONAWALLA', 'POWERGRID', 'PPLPHARMA', 'PSB', 'RAJESHEXPO', 'RECLTD', 'REDINGTON', 'RHIM', 'RVNL', 'SAIL', 'SBICARD', 'SBIN', 'SJVN', 'SONACOMS', 'STARHEALTH', 'SUMICHEM', 'SUNTV', 'SUVENPHAR', 'SYNGENE', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TRIDENT', 'TTML', 'UCOBANK', 'UNIONBANK', 'UNOMINDA', 'UPL', 'VEDL', 'WIPRO', 'YESBANK', 'ZEEL', 'ZOMATO', 'ZYDUSLIFE', 'AARTIDRUGS', 'ACI', 'AEGISCHEM', 'ALLCARGO', 'ALOKINDS', 'ANANTRAJ', 'APLLTD', 'ARVINDFASN', 'ASTERDM', 'AVANTIFEED', 'BALRAMCHIN', 'BARBEQUE', 'BIKAJI', 'BLS', 'BOROLTD', 'BORORENEW', 'BRIGADE', 'BSOFT', 'CANFINHOME', 'CASTROLIND', 'CCL', 'CENTURYPLY', 'CESC', 'CHALET', 'CHEMPLASTS', 'CMSINFO', 'CSBBANK', 'DCBBANK', 'DEEPAKFERT', 'DELTACORP', 'EASEMYTRIP', 'EDELWEISS', 'EIDPARRY', 'EIHOTEL', 'ENGINERSIN', 'EPL', 'EQUITASBNK', 'FDC', 'FINPIPE', 'FSL', 'FUSION', 'GAEL', 'GATEWAY', 'GESHIP', 'GHCL', 'GLENMARK', 'GLS', 'GMDCLTD', 'GNFC', 'GODREJAGRO', 'GPIL', 'GPPL', 'GRANULES', 'GRAPHITE', 'GREENLAM', 'GREENPANEL', 'GRSE', 'GSFC', 'GUJALKALI', 'HARSHA', 'HCG', 'HEIDELBERG', 'HFCL', 'HIKAL', 'HINDCOPPER', 'HSCL', 'HUDCO', 'IBREALEST', 'IBULHSGFIN', 'IEX', 'INDIACEM', 'INDOCO', 'INFIBEAM', 'INTELLECT', 'IONEXCHANG', 'IRCON', 'ITI', 'J&KBANK', 'JAMNAAUTO', 'JINDALPOLY', 'JINDWORLD', 'JKPAPER', 'JKTYRE', 'JMFINANCIL', 'JSL', 'JTEKTINDIA', 'JUBLINGREA', 'JUBLPHARMA', 'JUSTDIAL', 'JWL', 'JYOTHYLAB', 'KARURVYSYA', 'KFINTECH', 'KIRLOSENG', 'KNRCON', 'KRBL', 'KTKBANK', 'LAOPALA', 'LATENTVIEW', 'LEMONTREE', 'LXCHEM', 'MAHLIFE', 'MAHLOG', 'MANAPPURAM', 'MHRIL', 'MIDHANI', 'MINDACORP', 'MMTC', 'MRPL', 'NATCOPHARM', 'NAVA', 'NBCC', 'NCC', 'NETWORK18', 'NFL', 'NIITLTD', 'NLCINDIA', 'NOCIL', 'ORIENTELEC', 'PAISALO', 'PARADEEP', 'PCBL', 'PCJEWELLER', 'PDSL', 'PNCINFRA', 'PRAJIND', 'PRINCEPIPE', 'PRSMJOHNSN', 'QUESS', 'RAILTEL', 'RAIN', 'RAJRATAN', 'RALLIS', 'RBA', 'RBLBANK', 'RCF', 'RELIGARE', 'RELINFRA', 'RENUKA', 'RITES', 'RKFORGE', 'ROSSARI', 'RPOWER', 'RTNINDIA', 'RUSTOMJEE', 'SARDAEN', 'SAREGAMA', 'SCHNEIDER', 'SCI', 'SHARDACROP', 'SHOPERSTOP', 'SHYAMMETL', 'SIS', 'SOUTHBANK', 'SPARC', 'SPLPETRO', 'STARCEMENT', 'STLTECH', 'SUNTECK', 'SUPRAJIT', 'SWANENERGY', 'SWSOLAR', 'SYRMA', 'TARSONS', 'TATACOFFEE', 'TECHNOE', 'TINPLATE', 'TMB', 'TRITURBINE', 'TRIVENI', 'TTKPRESTIG', 'TV18BRDCST', 'UFLEX', 'UJJIVANSFB', 'USHAMART', 'UTIAMC', 'VAIBHAVGBL', 'VARROC', 'VGUARD', 'VIJAYA', 'VIPIND', 'VRLLOG', 'VTL', 'WELCORP', 'WELSPUNIND', 'WSTCSTPAPR', 'ZENSARTECH', 'ADFFOODS', 'ADVENZYMES', 'AHLUCONT', 'ALEMBICLTD', 'AMRUTANJAN', 'ANDHRAPAP', 'ANDHRSUGAR', 'APCOTEXIND', 'APOLLOPIPE', 'APTECHT', 'ARVIND', 'ARVSMART', 'ASHIANA', 'ASHOKA', 'ASTRAMICRO', 'ATFL', 'AVTNPL', 'BAJAJCON', 'BAJAJHIND', 'BALMLAWRIE', 'BANCOINDIA', 'BEPL', 'BFUTILITIE', 'BOMDYEING', 'BSHSL', 'CAMLINFINE', 'CANTABIL', 'CHENNPETRO', 'CHOICEIN', 'CONFIPET', 'COSMOFIRST', 'DALMIASUG', 'DATAMATICS', 'DBCORP', 'DBL', 'DBOL', 'DBREALTY', 'DCAL', 'DCW', 'DCXINDIA', 'DEN', 'DHAMPURSUG', 'DHANI', 'DOLLAR', 'DREAMFOLKS', 'DWARKESH', 'ELECTCAST', 'EMIL', 'EMUDHRA', 'EVEREADY', 'FCL', 'FILATEX', 'FINOPB', 'FMGOETZE', 'GABRIEL', 'GALLANTT', 'GANESHHOUC', 'GATI', 'GENESYS', 'GENUSPOWER', 'GMRP&UI', 'GNA', 'GOCLCORP', 'GOKULAGRO', 'GOLDIAM', 'GREAVESCOT', 'GREENPLY', 'GRMOVER', 'GTPL', 'GUFICBIO', 'GULFOILLUB', 'HBLPOWER', 'HCC', 'HEMIPROP', 'HERANBA', 'HERITGFOOD', 'HINDOILEXP', 'HINDWAREAP', 'HUHTAMAKI', 'ICIL', 'IFCI', 'IGPL', 'IIFLSEC', 'IMAGICAA', 'IMFA', 'INDIAGLYCO', 'INDORAMA', 'INOXGREEN', 'INOXWIND', 'INSECTICID', 'IOLCP', 'IPL', 'ISMTLTD', 'ITDC', 'ITDCEM', 'JAGRAN', 'JAICORPLTD', 'JAYNECOIND', 'JINDALSAW', 'JISLJALEQS', 'JKIL', 'KABRAEXTRU', 'KCP', 'KESORAMIND', 'KIRIINDUS', 'KKCL', 'KOLTEPATIL', 'KRSNAA', 'KSCL', 'KSL', 'LANDMARK', 'LUMAXTECH', 'MANALIPETC', 'MANINFRA', 'MARKSANS', 'MAYURUNIQ', 'MBAPL', 'MIRZAINT', 'MOIL', 'MOL', 'MONTECARLO', 'MOREPENLAB', 'MSTCLTD', 'MTNL', 'MUKANDLTD', 'NACLIND', 'NAVNETEDUL', 'NDTV', 'NELCO', 'NRBBEARING', 'OAL', 'OMAXE', 'OPTIEMUS', 'ORCHPHARMA', 'ORIENTCEM', 'PANAMAPET', 'PARAS', 'PFOCUS', 'PRICOLLTD', 'PSPPROJECT', 'PTC', 'PURVA', 'RAMASTEEL', 'RAMCOIND', 'RAMKY', 'RATEGAIN', 'REPCOHOME', 'RESPONIND', 'RSYSTEMS', 'RUPA', 'SAGCEM', 'SALASAR', 'SANDHAR', 'SANGHIIND', 'SANGHVIMOV', 'SBCL', 'SEPC', 'SEQUENT', 'SESHAPAPER', 'SHALBY', 'SHANKARA', 'SHANTIGEAR', 'SHILPAMED', 'SHK', 'SIRCA', 'SIYSIL', 'SJS', 'SOLARA', 'SOMANYCERA', 'SOTL', 'SPCENET', 'SPIC', 'SSWL', 'STAR', 'STOVEKRAFT', 'SUBEXLTD', 'SUBROS', 'SUDARSCHEM', 'SULA', 'SUNDARMHLD', 'SUNFLAG', 'SUPRIYA', 'SURYAROSNI', 'SUVEN', 'TCNSBRANDS', 'TDPOWERSYS', 'TEXRAIL', 'THOMASCOOK', 'THYROCARE', 'TI', 'TIMETECHNO', 'TIPSINDLTD', 'TIRUMALCHM', 'TNPL', 'TVTODAY', 'UJJIVAN', 'UNICHEMLAB', 'UNIPARTS', 'VALIANTORG', 'VERANDA', 'VIDHIING', 'VISHNU', 'WABAG', 'WELENT', 'WHEELS', 'WOCKPHARMA', '3IINFOLTD', '5PAISA', '63MOONS', 'AARTISURF', 'ADSL', 'AGSTRA', 'AHL', 'AJMERA', 'ALLSEC', 'APCL', 'APEX', 'APOLLO', 'ARIHANTCAP', 'ARIHANTSUP', 'ARTEMISMED', 'ASAL', 'ASALCBR', 'ASIANTILES', 'ATULAUTO', 'AVADHSUGAR', 'AWHCL', 'AXISCADES', 'AXITA', 'BAJAJHCARE', 'BALAXI', 'BBTCL', 'BCLIND', 'BFINVEST', 'BHAGERIA', 'BHARATWIRE', 'BIGBLOC', 'BLISSGVS', 'BLKASHYAP', 'BODALCHEM', 'CAPACITE', 'CENTENKA', 'CENTRUM', 'CHEMCON', 'CLSEL', 'COFFEEDAY', 'CONSOFINVT', 'CREATIVE', 'CREST', 'CSLFINANCE', 'DCMSRIND', 'DECCANCE', 'DEEPINDS', 'DHANBANK', 'DHARMAJ', 'DIGISPICE', 'DLINKINDIA', 'DMCC', 'DPABHUSHAN', 'DPSCLTD', 'DPWIRES', 'DREDGECORP', 'DVL', 'EIHAHOTELS', 'EKC', 'ELDEHSG', 'ELIN', 'EMAMIPAP', 'ENIL', 'ESTER', 'EXXARO', 'FAZE3Q', 'FOODSIN', 'GANDHITUBE', 'GANESHBE', 'GENUSPAPER', 'GEOJITFSL', 'GEPIL', 'GFLLIMITED', 'GICHSGFIN', 'GIPCL', 'GMBREW', 'GOACARBON', 'GREENPOWER', 'GULPOLY', 'HARDWYN', 'HARIOMPIPE', 'HERCULES', 'HEXATRADEX', 'HIMATSEIDE', 'HITECH', 'HITECHGEAR', 'HLVLTD', 'HPAL', 'HPL', 'HTMEDIA', 'IFBAGRO', 'IFGLEXPOR', 'IGARASHI', 'INDIANHUME', 'INDNIPPON', 'INDOAMIN', 'INFOBEAN', 'JAGSNPHARM', 'JAYAGROGN', 'JAYBARMARU', 'JINDRILL', 'JPOLYINVST', 'JUBLINDS', 'KAMDHENU', 'KANORICHEM', 'KELLTONTEC', 'KHAICHEM', 'KITEX', 'KOKUYOCMLN', 'KOPRAN', 'KRISHANA', 'KUANTUM', 'LIBERTSHOE', 'LIKHITHA', 'LINC', 'LINCOLN', 'MADRASFERT', 'MAGADSUGAR', 'MANAKSIA', 'MANGCHEFER', 'MANGLMCEM', 'MANINDS', 'MARATHON', 'MATRIMONY', 'MEDICAMEQ', 'MEDICO', 'MENONBE', 'MKPL', 'MONARCH', 'MUNJALAU', 'NAHARCAP', 'NAHARPOLY', 'NAHARSPING', 'NAVKARCORP', 'NCLIND', 'NECLIFE', 'NELCAST', 'NITINSPIN', 'NRAIL', 'NRL', 'NURECA', 'OCCL', 'ONMOBILE', 'ONWARDTEC', 'ORIENTBELL', 'ORIENTHOT', 'ORIENTPPR', 'OSWALAGRO', 'PANACEABIO', 'PARAGMILK', 'PATELENG', 'PENIND', 'PFS', 'PITTIENG', 'PLASTIBLEN', 'PNBGILTS', 'POKARNA', 'PRECAM', 'PRECWIRE', 'QUICKHEAL', 'RAMAPHO', 'RAMCOSYS', 'RAMRAT', 'REFEX', 'REPRO', 'RGL', 'RICOAUTO', 'ROHLTD', 'ROSSELLIND', 'ROTO', 'RPSGVENT', 'RSWM', 'RUBYMILLS', 'RUSHIL', 'SANGAMIND', 'SASTASUNDR', 'SATIA', 'SATIN', 'SATINDLTD', 'SCHAND', 'SCPL', 'SDBL', 'SHALPAINTS', 'SHEMAROO', 'SHIVALIK', 'SHREDIGCEM', 'SHREEPUSHK', 'SHREYAS', 'SHRIRAMPPS', 'SIGACHI', 'SKIPPER', 'SMCGLOBAL', 'SMSPHARMA', 'SNOWMAN', 'SPAL', 'SPECIALITY', 'SPENCERS', 'SPORTKING', 'SREEL', 'SRHHYPOLTD', 'STCINDIA', 'STEELCAS', 'STERTOOLS', 'SUKHJITS', 'SURYODAY', 'SUTLEJTEX', 'SWELECTES', 'TAJGVK', 'TALBROAUTO', 'TARC', 'TBZ', 'TEXINFRA', 'TFCILTD', 'THEMISMED', 'TNPETRO', 'TRACXN', 'TRIL', 'TVSELECT', 'UGARSUGAR', 'UGROCAP', 'UNIDT', 'UNIENTER', 'UNIVCABLES', 'UNIVPHOTO', 'UTTAMSUGAR', 'VASCONEQ', 'VIMTALABS', 'VINYLINDIA', 'VISAKAIND', 'VLSFINANCE', 'VSSL', 'WINDLAS', 'XCHANGING', 'YUKEN', 'ZIMLAB', 'ZOTA', 'ZUARI', 'AARVI', 'ADVANIHOTR', 'AHLEAST', 'AKSHARCHEM', 'ALMONDZ', 'ARIES', 'ARROWGREEN', 'ASAHISONG', 'ASIANENE', 'ASPINWALL', 'AURUM', 'AYMSYNTEX', 'BALAJITELE', 'BANSWRAS', 'BASML', 'BGRENERGY', 'BHARATGEAR', 'BIL', 'BIRLACABLE', 'BIRLAMONEY', 'BRNL', 'BSL', 'CAREERP', 'CHEMBOND', 'CHEMFAB', 'CLEDUCATE', 'COASTCORP', 'CYBERTECH', 'DCMNVL', 'DEEPENR', 'DELPHIFX', 'DEVIT', 'DICIND', 'DONEAR', 'DSSL', 'DTIL', 'DYCL', 'DYNPRO', 'EIFFL', 'EMAMIREAL', 'EMKAY', 'FOCUS', 'GEECEE', 'GINNIFILA', 'GLOBAL', 'GOKUL', 'GSS', 'GUJAPOLLO', 'HARRMALAYA', 'HINDCOMPOS', 'HIRECT', 'HITECHCORP', 'HMVL', 'HUBTOWN', 'ICEMAKE', 'INDOBORAX', 'INDOTHAI', 'INDSWFTLAB', 'INDTERRAIN', 'INSPIRISYS', 'INTLCONV', 'IRISDOREME', 'ISFT', 'JAYSREETEA', 'JINDALPHOT', 'KAMATHOTEL', 'KANPRPLA', 'KAYA', 'KECL', 'KMSUGAR', 'KOHINOOR', 'KOTHARIPET', 'KOTHARIPRO', 'KREBSBIO', 'KRITI', 'LOKESHMACH', 'LOVABLE', 'LOYALTEX', 'LYKALABS', 'MAANALU', 'MAHAPEXLTD', 'MAHEPC', 'MAHESHWARI', 'MANAKSTEEL', 'MANGALAM', 'MANORG', 'MARALOVER', 'MAWANASUG', 'MAXIND', 'MBLINFRA', 'MCLEODRUSS', 'MEGASTAR', 'MHLXMIRU', 'MINDTECK', 'MMP', 'MODISONLTD', 'MOLDTECH', 'MUNJALSHOW', 'MUTHOOTCAP', 'NAHARINDUS', 'NATHBIOGEN', 'NDL', 'ORBTEXP', 'ORICONENT', 'OSIAHYPER', 'OSWALSEEDS', 'PALREDTEC', 'PAR', 'PASUPTAC', 'PAVNAIND', 'PDMJEPAPER', 'PENINLAND', 'PODDARMENT', 'PONNIERODE', 'PPAP', 'PPL', 'PRECOT', 'PRIMESECU', 'PTL', 'RADHIKAJWE', 'RAJTV', 'RANASUG', 'REPL', 'RITCO', 'RPPL', 'RUCHIRA', 'SAKAR', 'SAKHTISUG', 'SALZERELEC', 'SARLAPOLY', 'SBC', 'SECURKLOUD', 'SELAN', 'SIGMA', 'SILINV', 'SILVERTUC', 'SINTERCOM', 'SKMEGGPROD', 'SMLT', 'SMSLIFE', 'SPLIL', 'STARPAPER', 'STEL', 'SUPERHOUSE', 'TAKE', 'THEINVEST', 'TOTAL', 'TPLPLASTEH', 'TRF', 'TRIGYN', 'TTL', 'UNITEDPOLY', 'VARDHACRLC', 'VENUSREM', 'VERTOZ', 'VETO', 'VIPCLOTHNG', 'WEBELSOLAR', 'WINDMACHIN', 'XELPMOC', 'ZODIACLOTH', 'ZUARIIND', 'AAATECH', 'AARON', 'AARVEEDEN', 'ACEINTEG', 'AGROPHOS', 'AHLADA', 'AKASH', 'AKG', 'ALKALI', 'ALPA', 'ALPHAGEO', 'AMDIND', 'AMJLAND', 'ANIKINDS', 'ANMOL', 'ARCHIES', 'ARTNIRMAN', 'ARVEE', 'ATLANTA', 'AVG', 'AVROIND', 'BALPHARMA', 'BANARBEADS', 'BANG', 'BANKA', 'BIOFILCHEM', 'BLBLIMITED', 'BTML', 'BYKE', 'CAPTRUST', 'COMPUSOFT', 'CORALFINAC', 'CORDSCABLE', 'CTE', 'DAMODARIND', 'DCM', 'DGCONTENT', 'DHRUV', 'DJML', 'EMMBI', 'ENERGYDEV', 'FIBERWEB', 'GANGESSECU', 'GILLANDERS', 'GLOBALVECT', 'HECPROJECT', 'HILTON', 'HISARMETAL', 'HOVS', 'INDIANCARD', 'INTENTECH', 'IRIS', 'IVP', 'JAIPURKURT', 'JHS', 'JMA', 'JOCIL', 'KAKATCEM', 'KHANDSE', 'LAGNAM', 'LAMBODHARA', 'LASA', 'LATTEYS', 'LOTUSEYE', 'MAHASTEEL', 'MALUPAPER', 'MANAKALUCO', 'MCL', 'MITCON', 'MORARJEE', 'MRO-TEK', 'NAGREEKEXP', 'NECCLTD', 'NGIL', 'NIBL', 'OBCL', 'OMAXAUTO', 'ORIENTLTD', 'PNC', 'PRITI', 'RANEENGINE', 'RELCHEMQ', 'RKEC', 'ROML', 'SALONA', 'SHIVAMILLS', 'SHIVATEX', 'SHRADHA', 'SIKKO', 'SIMBHALS', 'SMARTLINK', 'STARTECK', 'STEELCITY', 'SUMIT', 'SURANASOL', 'SURYALAXMI', 'TAINWALCHM', 'TARMAT', 'TEMBO', 'TERASOFT', 'TEXMOPIPES', 'TOKYOPLAST', 'TREEHOUSE', 'UMAEXPORTS', 'UMANGDAIRY', 'UNITEDTEA', 'URAVI', 'VAISHALI', 'VINEETLAB', 'WORTH', '21STCENMGM', '3PLAND', 'BALKRISHNA', 'CROWN', 'HBSL', 'KARMAENG', 'KHAITANLTD', 'LAXMICOT', 'LFIC', 'MADHAV', 'MARSHALL', 'PEARLPOLY', 'SAGARDEEP', 'SANGINITA', 'SILGO', 'TIMESGTY', 'WILLAMAGOR', 'ZENITHEXPO']
# since 1m data were irregular like 9:15 followed by 10:12 so all the stocks were loaded together
stock_list_df = yf.download(tickers=[f"{st}.NS" for st in stocks_list], period='1wk', interval='1m', progress=True)['Close']
stock_list_df.index = pd.to_datetime(stock_list_df.index)
stock_list_df = stock_list_df.loc["2023-11-17":]
stock_list_df = stock_list_df.bfill().ffill().dropna(axis=1)
print(stock_list_df)
stocks_counter = 0  # index as counter
stocks_df = stock_list_df.copy()  # here key is symbol name and value is one day price data


@app.route("/price")
def get_price():
    global stock_list_df, stock_df, stock_counter
    if 'symbol' in request.args.keys():
        symbol = str(request.args['symbol']).upper()

        if symbol not in stock_df.keys():
            # if DATA_FROM_FILE:
            #     for file in os.listdir():
            #         if 'csv' in file and symbol in file:
            #             stock_counter[file.rsplit('.', 1)[0]] = -1
            #             stock_df[file.rsplit('.', 1)[0]] = pd.read_csv(file)
            # else:
            #     t = yf.download(tickers=f"{symbol}.NS", period='1wk', interval='1m')[['Close']]
            #     t = t.bfill().ffill()
            #     t.columns = ['price']
            #     stock_df[symbol] = t.loc[date]
            #     stock_counter[symbol] = -1

            t = stock_list_df[[f"{symbol}.NS"]]
            t.columns = ['price']
            stock_df[symbol] = t.loc[date]
            stock_counter[symbol] = -1



        try:
            if symbol in stock_counter.keys():
                stock_counter[symbol] += 1
                return {'data': stock_df[symbol].price.iloc[stock_counter[symbol]]}
        except IndexError:

            return {'data': 'ENDED'}
        else:
            return {"msg": "Wrong symbol provided"}

    return {'msg': 'does not contain symbol as key'}


@app.route("/prices")
def get_prices():
    global stocks_df, stocks_counter
    try:
        one_row: pd.Series = stocks_df.iloc[stocks_counter]
        stocks_counter += 1
    except IndexError:
        return {'data': 'ENDED'}
    return {'data': one_row.to_dict()}


if __name__ == '__main__':
    app.run(port=8082)
